### PR TITLE
Improve actions

### PR DESCRIPTION
**Pull request by zaeph**

### CODE REVIEW

**Comment by zaeph** [comment]
Not sure about making this an error.

**Comment by myshevchuk** [comment]
Well, it is a user error.

**Comment by zaeph** [comment]
True, but sometimes, I don't know whether something should just be feedback or an actual error.

**Comment by myshevchuk** [comment]
You decide :)

**Comment by zaeph** [comment]
`user-error` is fine, I won't lose sleep over it. 🤡

**Pull request merged**
