### PR TITLE
fix orb-find-note-file

### PR DESCRIPTION
**Pull request by myshevchuk**

### CODE REVIEW

**Comment by zaeph** [comment]
Oof, actually, we've just reverted to alist.  Sorry, should have warned you!

**Comment by myshevchuk** [comment]
Ok. Is it possible to remove this commit?

**Comment by zaeph** [comment]
I'll take care of it soon, waiting on the final PR merge upstream, then I'll revert everything in a PR.  I'll also fix our `find-non-ref` commands.

**Comment by myshevchuk** [comment]
Please let me know as soon as it's done. I have to suspend my work now because I cannot test things.

**Pull request merged**
